//==============================================================================
// pf_ccc_behavioral.sv
//
// Behavioral replacement for the Microchip PF_CCC PLL (50 MHz -> 125 MHz)
// used by the mpf300 FMCOMMS2 design, for Verilator simulation. Counterpart
// of the Xilinx flow's clk_wiz_behavioral.sv: the real PF_CCC is a
// generated core (Actel:SgCore:PF_CCC) whose simulation model is encrypted
// vendor IP — not usable in Verilator.
//
// Port names deliberately match the clk_wiz behavioral shim so the tb_top
// instantiation changes only in the module name (the mpf300 design's
// refclk_ibuf INBUF+CLKINT input path is a pass-through in simulation and
// is folded into this model):
//
//   clk_in1_p  <- 50 MHz board oscillator (PF_CCC REF_CLK_0; _n ignored,
//                 the Splash Kit oscillator is single-ended)
//   resetn     <- testbench reset (the real PF_CCC free-runs with
//                 PLL_POWERDOWN_N tied high; lock-drop on reset is kept
//                 from the clk_wiz shim so the TB reset sequencing works
//                 the same way)
//   clk_out1   -> 125 MHz fabric clock (PF_CCC OUT0_FABCLK_0)
//   clk_out2   -> reference pass-through (unused by the TB)
//   locked     -> PLL_LOCK_0, asserts 16 reference cycles after reset
//                 release (real lock time is far longer; irrelevant for
//                 behavioral sim)
//
// The 125 MHz output is generated by a free-running oscillator rather than
// derived from the reference (50 -> 125 MHz is not an integer division);
// it is held low while resetn is asserted, like the clk_wiz shim held its
// divide-by-2 output.
//==============================================================================

`timescale 1ns / 1ps

module pf_ccc_behavioral (
    output wire clk_out1,     // 125 MHz (OUT0_FABCLK_0)
    output wire clk_out2,     // reference pass-through
    input  wire resetn,
    output reg  locked,
    input  wire clk_in1_p,    // 50 MHz reference
    input  wire clk_in1_n     // ignored (single-ended oscillator)
);

    // 125 MHz output oscillator, held low in reset
    reg clk125 = 1'b0;
    always #4ns begin
        if (resetn) clk125 = ~clk125;
        else        clk125 = 1'b0;
    end
    assign clk_out1 = clk125;

    assign clk_out2 = clk_in1_p;

    // lock: 16 reference cycles after reset release
    reg [4:0] lock_cnt = 5'd0;
    always @(posedge clk_in1_p or negedge resetn) begin
        if (!resetn) begin
            lock_cnt <= 5'd0;
            locked   <= 1'b0;
        end else if (!locked) begin
            lock_cnt <= lock_cnt + 5'd1;
            if (lock_cnt == 5'd15)
                locked <= 1'b1;
        end
    end

    wire unused_clk_in1_n = clk_in1_n;

endmodule
