//------------------------------------------------------------------------------
// pf_ccc_sim.v — behavioral stand-in for the PF_CCC PLL (50 MHz -> 125 MHz)
// used by the mpf300 FMCOMMS2 design, for the full-system Questa simulation.
//
// The real PF_CCC is a Libero-generated core whose simulation model lives in
// disposable project output; this model keeps the sim self-contained (same
// pattern as the Xilinx 5.7 sim's clk_wiz handling, and the Verilator sims'
// pf_ccc_behavioral). Port names match the generated core's used subset.
//
// Like the silicon PLL (PLL_POWERDOWN_N tied high in the SmartDesign), it
// free-runs from time zero: the 125 MHz output starts immediately and
// PLL_LOCK_0 asserts after 16 reference cycles (~320 ns; real lock time is
// far longer, irrelevant for behavioral sim). System reset is downstream
// (sys_ctrl), not a PLL input.
//
// 50 -> 125 MHz is not an integer relation, so the output is generated by a
// free-running oscillator rather than derived from the reference.
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

module pf_ccc_sim (
    input  wire REF_CLK_0,
    input  wire PLL_POWERDOWN_N_0,
    output reg  OUT0_FABCLK_0 = 1'b0,
    output reg  PLL_LOCK_0 = 1'b0
);

    // 125 MHz fabric clock (8 ns period), free-running
    always #4 OUT0_FABCLK_0 = ~OUT0_FABCLK_0;

    // lock after 16 reference cycles
    reg [4:0] lock_cnt = 5'd0;
    always @(posedge REF_CLK_0) begin
        if (PLL_POWERDOWN_N_0 && !PLL_LOCK_0) begin
            lock_cnt <= lock_cnt + 5'd1;
            if (lock_cnt == 5'd15)
                PLL_LOCK_0 <= 1'b1;
        end
    end

endmodule

//------------------------------------------------------------------------------
// pf_init_monitor_sim — behavioral stand-in for PF_INIT_MONITOR: device
// initialization (fabric configuration + LSRAM init) completes ~1 us after
// time zero.
//------------------------------------------------------------------------------

module pf_init_monitor_sim (
    output reg DEVICE_INIT_DONE = 1'b0
);

    initial begin
        #1000;
        DEVICE_INIT_DONE = 1'b1;
    end

endmodule

//------------------------------------------------------------------------------
// PF_CCC_C1 — behavioral stand-in for the second Libero-generated CCC added
// by the TX FB_CLK phase-pair change (deps/hdl a6df9cdc4): ad_data_clk.v
// with USE_PLL_90=1 instantiates it BY THIS NAME to derive the 0/90-degree
// l_clk pair from the AD9361 DATA_CLK (61.44 MHz). Behavioral model:
// OUT0 follows the reference (0 deg), OUT1 is the reference delayed by a
// quarter of the measured period (90 deg), lock after 16 reference cycles.
// Period is re-measured continuously, so the model tracks the TB's clock
// including the power-gate stop/restart window.
//------------------------------------------------------------------------------

module PF_CCC_C1 (
    input  wire PLL_POWERDOWN_N_0,
    input  wire REF_CLK_0,
    output wire OUT0_FABCLK_0,
    output reg  OUT1_FABCLK_0 = 1'b0,
    output reg  PLL_LOCK_0 = 1'b0
);

    // 0-degree output: phase-aligned to the reference
    assign OUT0_FABCLK_0 = REF_CLK_0;

    // measure the reference period
    realtime t_last = 0.0;
    realtime period = 0.0;
    always @(posedge REF_CLK_0) begin
        if (t_last > 0.0)
            period <= $realtime - t_last;
        t_last <= $realtime;
    end

    // 90-degree output: reference delayed a quarter period (transport)
    always @(REF_CLK_0)
        if (period > 0.0)
            OUT1_FABCLK_0 <= #(period / 4.0) REF_CLK_0;

    // lock after 16 reference cycles
    reg [4:0] lock_cnt = 5'd0;
    always @(posedge REF_CLK_0) begin
        if (PLL_POWERDOWN_N_0 && !PLL_LOCK_0 && period > 0.0) begin
            lock_cnt <= lock_cnt + 5'd1;
            if (lock_cnt == 5'd15)
                PLL_LOCK_0 <= 1'b1;
        end
    end

endmodule
