//------------------------------------------------------------------------------
// pf_ccc_sim.v — behavioral stand-in for the PF_CCC PLL (50 MHz -> 125 MHz)
// used by the mpf300 FMCOMMS2 design, for the full-system Questa simulation.
//
// The real PF_CCC is a Libero-generated core whose simulation model lives in
// disposable project output; this model keeps the sim self-contained (same
// pattern as the Xilinx 5.7 sim's clk_wiz handling, and the Verilator sims'
// pf_ccc_behavioral). Port names match the generated core's used subset.
//
// Like the silicon PLL (PLL_POWERDOWN_N tied high in the SmartDesign), it
// free-runs from time zero: the 125 MHz output starts immediately and
// PLL_LOCK_0 asserts after 16 reference cycles (~320 ns; real lock time is
// far longer, irrelevant for behavioral sim). System reset is downstream
// (sys_ctrl), not a PLL input.
//
// 50 -> 125 MHz is not an integer relation, so the output is generated by a
// free-running oscillator rather than derived from the reference.
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

module pf_ccc_sim (
    input  wire REF_CLK_0,
    input  wire PLL_POWERDOWN_N_0,
    output reg  OUT0_FABCLK_0 = 1'b0,
    output reg  PLL_LOCK_0 = 1'b0
);

    // 125 MHz fabric clock (8 ns period), free-running
    always #4 OUT0_FABCLK_0 = ~OUT0_FABCLK_0;

    // lock after 16 reference cycles
    reg [4:0] lock_cnt = 5'd0;
    always @(posedge REF_CLK_0) begin
        if (PLL_POWERDOWN_N_0 && !PLL_LOCK_0) begin
            lock_cnt <= lock_cnt + 5'd1;
            if (lock_cnt == 5'd15)
                PLL_LOCK_0 <= 1'b1;
        end
    end

endmodule

//------------------------------------------------------------------------------
// pf_init_monitor_sim — behavioral stand-in for PF_INIT_MONITOR: device
// initialization (fabric configuration + LSRAM init) completes ~1 us after
// time zero.
//------------------------------------------------------------------------------

module pf_init_monitor_sim (
    output reg DEVICE_INIT_DONE = 1'b0
);

    initial begin
        #1000;
        DEVICE_INIT_DONE = 1'b1;
    end

endmodule
